src/main/kotlin/com/pubnub/api/Endpoint.kt
src/main/kotlin/com/pubnub/api/PNConfiguration.kt
src/main/kotlin/com/pubnub/api/PubNub.kt
src/main/kotlin/com/pubnub/api/PubNubUtil.kt
src/main/kotlin/com/pubnub/api/builder/PubSub.kt
src/main/kotlin/com/pubnub/api/endpoints/access/Grant.kt
src/main/kotlin/com/pubnub/api/endpoints/access/GrantToken.kt
src/main/kotlin/com/pubnub/api/endpoints/access/RevokeToken.kt
src/main/kotlin/com/pubnub/api/endpoints/files/PublishFileMessage.kt
src/main/kotlin/com/pubnub/api/endpoints/presence/Heartbeat.kt
src/main/kotlin/com/pubnub/api/endpoints/pubsub/Publish.kt
src/main/kotlin/com/pubnub/api/endpoints/remoteaction/RemoteAction.kt
src/main/kotlin/com/pubnub/api/managers/BasePathManager.kt
src/main/kotlin/com/pubnub/api/managers/SubscriptionManager.kt
src/main/kotlin/com/pubnub/api/presence/Presence.kt
src/main/kotlin/com/pubnub/api/presence/Utils.kt
src/main/kotlin/com/pubnub/api/presence/internal/Utils.kt
src/main/kotlin/com/pubnub/api/subscribe/Subscribe.kt
src/main/kotlin/com/pubnub/api/subscribe/Utils.kt
src/main/kotlin/com/pubnub/api/subscribe/internal/Utils.kt
src/main/kotlin/com/pubnub/api/vendor/FileEncryptionUtil.kt
src/main/kotlin/com/pubnub/api/workers/SubscribeMessageWorker.kt
src/main/kotlin/com/pubnub/extension/JsonElement.kt

Improvements are not yet implemented therefore if enabled it will
throw runtime exception

Add config flag enabling experimental subscribe improvements 

---

pubnub-entities/src/main/kotlin/com/pubnub/entities/Space.kt
pubnub-entities/src/main/kotlin/com/pubnub/entities/User.kt

get -> fetch
set -> create + update

Renamed methods.

---

pubnub-users/gradle.properties
pubnub-users/settings.gradle

feat: Initial version of users module

Add empty settings.gradle

---

pubnub-users/gradle.properties

feat: Initial version of users module

Add group required by release process

---

.github/workflows/release.yml
.github/workflows/release/bom-maven-build.sh
.github/workflows/release/bom-maven-publish.sh
.github/workflows/release/kotlin-maven-build.sh
.github/workflows/release/kotlin-maven-publish.sh
.github/workflows/release/products.json
.github/workflows/release/spaces-maven-build.sh
.github/workflows/release/spaces-maven-publish.sh
.github/workflows/release/users-maven-build.sh
.github/workflows/release/users-maven-publish.sh

build(monorepo): add ability to override default release
Add ability to override default release process for monorepo with custom scripts for each product.

Add ability to override default release

---

pubnub-memberships/src/integrationTest/kotlin/com/pubnub/entities/MembershipIntegTest.kt
pubnub-memberships/src/main/kotlin/com/pubnub/entities/MembershipExtension.kt
pubnub-memberships/src/test/kotlin/com/pubnub/entities/MembershipExtensionKtTest.kt
pubnub-spaces/gradle.properties

feat: Initial space module release

Fix parameter name

---

build.gradle
pubnub-memberships/build.gradle
pubnub-spaces/build.gradle
pubnub-users/build.gradle
settings.gradle

Subprojects cleanup

---

src/integrationTest/kotlin/com/pubnub/api/integration/pam/GrantTokenIntegrationTest.kt
src/main/kotlin/com/pubnub/api/models/consumer/access_manager/sum/SpacePermissions.kt
src/test/kotlin/com/pubnub/api/endpoints/access/GrantTokenTest.kt

fix: Rename name to id in SpacePermissions

Renamed name to id in SpacePermissions

---

pubnub-kotlin-bom/gradle.properties

feat: pubnub-kotlin minor version bump

BOM release

---

gradle.properties

fix: Upgrade of vulnerable libs: Gson, logback
fix: Removed "create" for space as a valid permission that can be assigned to token.

@client-engineering-bot release kotlin as v7.3.2

---

pubnub-users/gradle.properties

fix: Deleted duplicated UserId class.

Release pubnub-users v0.2.1

---

pubnub-kotlin-bom/gradle.properties

feat: pubnub-kotlin patch version bump

Release Bom v0.2.1

---

.gitignore
.pubnub.yml
CHANGELOG.md
README.md
gradle.properties
src/main/kotlin/com/pubnub/api/PubNub.kt
src/main/kotlin/com/pubnub/api/managers/MapperManager.kt
src/main/kotlin/com/pubnub/api/models/consumer/pubsub/BasePubSubResult.kt
src/main/kotlin/com/pubnub/api/models/consumer/pubsub/PNEvent.kt
src/main/kotlin/com/pubnub/api/models/consumer/pubsub/PNPresenceEventResult.kt
src/main/kotlin/com/pubnub/api/models/consumer/pubsub/files/PNFileEventResult.kt
src/main/kotlin/com/pubnub/api/models/server/SubscribeMessage.kt
src/main/kotlin/com/pubnub/api/workers/SubscribeMessageProcessor.kt
src/main/kotlin/com/pubnub/api/workers/SubscribeMessageWorker.kt
src/test/kotlin/com/pubnub/api/legacy/PubNubTest.kt
src/test/kotlin/com/pubnub/api/workers/SubscribeMessageProcessorTest.kt
src/test/kotlin/com/pubnub/api/workers/SubscribeMessageWorkerJsonMessageParametrizedTest.kt
src/test/kotlin/com/pubnub/contract/RunMainCucumberTest.kt

feat: PNFileEventResult has messageJson field with the same JsonElement type as in other events

Expose jsonMessage for file events

---

gradle.properties

Added params responsible for signing release.

---

pubnub-memberships/src/integrationTest/kotlin/com/pubnub/membership/MembershipIntegTest.kt
src/integrationTest/kotlin/com/pubnub/api/integration/pam/AccessManagerIntegrationTest.kt
src/main/kotlin/com/pubnub/api/endpoints/FetchMessages.kt
src/main/kotlin/com/pubnub/api/endpoints/presence/HereNow.kt
src/main/kotlin/com/pubnub/api/models/consumer/presence/PNHereNow.kt
src/main/kotlin/com/pubnub/api/models/server/history/ServerFetchMessageItem.kt
src/main/kotlin/com/pubnub/api/services/PresenceService.kt
src/test/kotlin/com/pubnub/api/legacy/endpoints/history/FetchMessagesEndpointTest.kt
src/test/kotlin/com/pubnub/api/legacy/endpoints/presence/HereNowEndpointTest.kt
src/test/kotlin/com/pubnub/api/suite/presence/HereNowTestSuite.kt
src/test/kotlin/com/pubnub/contract/history/HistoryState.kt
src/test/kotlin/com/pubnub/contract/history/HistorySteps.kt
src/test/kotlin/com/pubnub/contract/parameter/BooleanType.kt
src/test/kotlin/com/pubnub/contract/presence/PresenceState.kt
src/test/kotlin/com/pubnub/contract/presence/PresenceSteps.kt
src/test/kotlin/com/pubnub/contract/step/KeysetStep.kt
src/test/kotlin/com/pubnub/contract/step/ThenSteps.kt
src/test/kotlin/com/pubnub/contract/subscribe/SubscribeState.kt
src/test/kotlin/com/pubnub/contract/subscribe/SubscribeSteps.kt

I would like to change how those steps are organized a little. New approached is already present in this PR. Other should come afterwards. What was wrong IMHO is that I named all steps regarding of the feature the same e.g. `WhenSteps`, `GivenSteps` which made it harder to navigate the code. I still feel pretty strongly about grouping them per feature, but the feature name should be in the name file as well. Also I don't think the packages `step`, `state`, etc. are so important. We can of course talk about it and if necessary I can adjust this change back to the old structure

Subscribe mt si contract test

---

.github/CODEOWNERS

build(codeowners): add  'are' as code owner

---

.github/workflows/release.yml

build(docs): update path for docs
Update path from which documentation uploaded to GitHub Pages.

Update path for docs

---

.github/workflows/run-tests.yml
src/main/kotlin/com/pubnub/api/subscribe/eventengine/event/Event.kt
src/main/kotlin/com/pubnub/api/subscribe/eventengine/state/SubscribeState.kt
src/test/kotlin/com/pubnub/api/subscribe/eventengine/worker/TransitionFromHandshakeFailedStateTest.kt
src/test/kotlin/com/pubnub/api/subscribe/eventengine/worker/TransitionFromHandshakeStoppedStateTest.kt
src/test/kotlin/com/pubnub/api/subscribe/eventengine/worker/TransitionFromHandshakingReconnectingStateTest.kt
src/test/kotlin/com/pubnub/api/subscribe/eventengine/worker/TransitionFromHandshakingStateTest.kt
src/test/kotlin/com/pubnub/api/subscribe/eventengine/worker/TransitionFromReceiveFailedStateTest.kt
src/test/kotlin/com/pubnub/api/subscribe/eventengine/worker/TransitionFromReceiveStoppedStateTest.kt
src/test/kotlin/com/pubnub/api/subscribe/eventengine/worker/TransitionFromReceivingReconnectingStateTest.kt
src/test/kotlin/com/pubnub/api/subscribe/eventengine/worker/TransitionFromReceivingStateTest.kt

Implement changes to transitions.

---

src/main/kotlin/com/pubnub/api/enums/PNStatusCategory.kt
src/main/kotlin/com/pubnub/api/subscribe/eventengine/state/SubscribeState.kt
src/test/kotlin/com/pubnub/api/subscribe/eventengine/worker/TransitionFromReceivingReconnectingStateTest.kt

Added status PNDisconnectedUnexpectedly

---

src/main/kotlin/com/pubnub/api/presence/eventengine/effect/PresenceEffectInvocation.kt
src/main/kotlin/com/pubnub/api/presence/eventengine/event/PresenceEvent.kt
src/main/kotlin/com/pubnub/api/presence/eventengine/state/PresenceState.kt
src/test/kotlin/com/pubnub/api/presence/eventengine/state/transition/TransitionFromHeartbeatCooldownStateTest.kt
src/test/kotlin/com/pubnub/api/presence/eventengine/state/transition/TransitionFromHeartbeatReconnectingStateTest.kt
src/test/kotlin/com/pubnub/api/presence/eventengine/state/transition/TransitionFromHeartbeatingStateTest.kt

Replaced NEXT_HEARTBEAT with TIMES_UP

Replaced HeartbeatWaiting with HeartbeatCooldown.

---

src/main/kotlin/com/pubnub/api/subscribe/eventengine/state/SubscribeState.kt
src/test/kotlin/com/pubnub/api/subscribe/eventengine/worker/TransitionFromHandshakeStoppedStateTest.kt
src/test/kotlin/com/pubnub/api/subscribe/eventengine/worker/TransitionFromReceiveStoppedStateTest.kt

Jira: https://pubnub.atlassian.net/browse/CLEN-1412
Decision: https://github.com/pubnub/ce-decisions/blob/master/decisions/00032%20-%20Predictability%20of%20disconnect%20and%20reconnect.md

Adjust transition according new requirements:

---

src/integrationTest/kotlin/com/pubnub/api/integration/PresenceIntegrationTests.kt
src/integrationTest/kotlin/com/pubnub/api/integration/SubscribeIntegrationTests.kt
src/main/kotlin/com/pubnub/api/PNConfiguration.kt
src/main/kotlin/com/pubnub/api/PubNub.kt
src/main/kotlin/com/pubnub/api/PubNubUtil.kt
src/main/kotlin/com/pubnub/api/endpoints/presence/Heartbeat.kt
src/main/kotlin/com/pubnub/api/endpoints/presence/Leave.kt
src/main/kotlin/com/pubnub/api/endpoints/presence/WhereNow.kt
src/main/kotlin/com/pubnub/api/endpoints/pubsub/Subscribe.kt
src/main/kotlin/com/pubnub/api/managers/RetrofitManager.kt
src/main/kotlin/com/pubnub/api/subscribe/Subscribe.kt
src/test/kotlin/com/pubnub/contract/step/KeysetStep.kt

Change enableSubscribeBeta flag to enableEventEngine 
Add "ee" query parameter to requests if enableEventEngine=true

EventEngine beta flag handling changes

---

src/integrationTest/kotlin/com/pubnub/api/integration/SubscribeIntegrationTests.kt
src/main/kotlin/com/pubnub/api/Endpoint.kt
src/main/kotlin/com/pubnub/api/PubNub.kt
src/main/kotlin/com/pubnub/api/presence/Presence.kt
src/main/kotlin/com/pubnub/api/presence/eventengine/effect/PresenceEffectFactory.kt
src/main/kotlin/com/pubnub/api/presence/eventengine/effect/WaitEffect.kt
src/main/kotlin/com/pubnub/api/retry/RetryableCallback.kt
src/main/kotlin/com/pubnub/api/subscribe/Subscribe.kt
src/main/kotlin/com/pubnub/api/subscribe/eventengine/effect/SubscribeEffectFactory.kt
src/test/kotlin/com/pubnub/api/eventengine/EffectDispatcherTest.kt
src/test/kotlin/com/pubnub/api/eventengine/EventEngineTest.kt
src/test/kotlin/com/pubnub/api/presence/PresenceTest.kt
src/test/kotlin/com/pubnub/api/presence/eventengine/effect/WaitEffectTest.kt
src/test/kotlin/com/pubnub/api/retry/RetryableCallbackTest.kt

Instead of creating single thread in some places we will use threadPool and reuse threads.

Introduced threadPool.

---

pubnub-core/pubnub-core-impl/src/main/kotlin/com/pubnub/internal/v2/subscription/BaseSubscriptionImpl.kt
pubnub-gson/build.gradle.kts
pubnub-gson/src/integrationTest/java/com/pubnub/api/integration/SubscribeIntegrationTests.java
pubnub-gson/src/main/java/com/pubnub/internal/v2/callbacks/DelegatingEventListener.java
pubnub-gson/src/main/java/com/pubnub/internal/v2/subscription/EmitterHelper.kt
pubnub-gson/src/main/java/com/pubnub/internal/v2/subscription/SubscriptionImpl.kt
pubnub-gson/src/main/java/com/pubnub/internal/v2/subscription/SubscriptionSetImpl.kt
pubnub-gson/src/test/kotlin/com/pubnub/internal/v2/subscription/SubscriptionImplTest.kt
pubnub-gson/src/test/kotlin/com/pubnub/internal/v2/subscription/SubscriptionSetImplTest.kt
pubnub-kotlin/build.gradle.kts
pubnub-kotlin/src/integrationTest/kotlin/com/pubnub/api/integration/SubscribeIntegrationTests.kt
pubnub-kotlin/src/test/kotlin/com/pubnub/internal/v2/subscription/SubscriptionSetImplTest.kt

I have just moved event emitter. For now I don't have simple solution how to move emitterHelper to constructor.

Moved EventEmitter to constructor.

---

pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/PubNubImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/FetchMessages.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/MessageCounts.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/channel_groups/AllChannelsChannelGroup.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/channel_groups/ListAllChannelGroup.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/files/DownloadFile.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/message_actions/AddMessageAction.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/message_actions/GetMessageActions.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/presence/HereNow.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/presence/WhereNow.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/v2/callbacks/EventListener.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/v2/callbacks/StatusListener.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/internal/entities/ChannelGroupImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/internal/entities/ChannelImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/internal/entities/ChannelMetadataImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/internal/entities/UserMetadataImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/internal/subscription/SubscriptionImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/internal/subscription/SubscriptionSetImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/kmp/Converters.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/kmp/factories.ios.kt

- Wrapping entities and Subscription/SubscriptionSet
- Reduced number of classes in Objective-C wrapper and adjust `iosMain` to these changes

Wrapping entities and Subscription/SubscriptionSet

---

pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/PubNubImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/FetchMessages.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/MessageCounts.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/files/DownloadFile.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/files/GetFileUrl.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/files/ListFiles.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/presence/GetState.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/endpoints/presence/HereNow.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/v2/PNConfiguration.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/v2/callbacks/StatusListener.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/kmp/Converters.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/kmp/factories.ios.kt

* Getting rid of warning related with Maps
* Ensuring that JsonImpl is used as expected
* Added some missing implementations in PubNubImpl.kt

Minor improvements

---

pubnub-core/pubnub-core-api/src/main/kotlin/com/pubnub/api/retry/RetryConfiguration.kt
pubnub-core/pubnub-core-api/src/main/kotlin/com/pubnub/api/v2/BasePNConfiguration.kt
pubnub-core/pubnub-core-api/src/main/kotlin/com/pubnub/api/v2/BasePNConfigurationOverride.kt
pubnub-core/pubnub-core-impl/src/main/kotlin/com/pubnub/internal/v2/BasePNConfigurationImpl.kt
pubnub-core/pubnub-core-impl/src/test/kotlin/com/pubnub/test/TestPNConfigurationImpl.kt
pubnub-gson/pubnub-gson-api/src/main/java/com/pubnub/api/PNConfiguration.kt
pubnub-gson/pubnub-gson-api/src/main/java/com/pubnub/api/v2/PNConfiguration.kt
pubnub-gson/pubnub-gson-impl/src/integrationTest/java/com/pubnub/api/integration/RetryConfigurationIntegrationTest.java
pubnub-gson/pubnub-gson-impl/src/integrationTest/java/com/pubnub/api/integration/managers/subscription/AbstractReconnectionProblemIT.java
pubnub-gson/pubnub-gson-impl/src/integrationTest/java/com/pubnub/api/integration/managers/subscription/ReconnectionProblemWithReconnectionPolicyIT.java
pubnub-gson/pubnub-gson-impl/src/integrationTest/java/com/pubnub/api/integration/util/BaseIntegrationTest.java
pubnub-kotlin/pubnub-kotlin-impl/src/integrationTest/kotlin/com/pubnub/api/integration/BaseIntegrationTest.kt
pubnub-kotlin/pubnub-kotlin-impl/src/integrationTest/kotlin/com/pubnub/api/integration/ObjectsIntegrationTest.kt

for subscribe by default. [CLEN-2236]

Enable retryConfiguration with exponential strategy

---

build-logic/gradle-plugins/src/main/kotlin/com/pubnub/gradle/PubNubKotlinMultiplatformPlugin.kt
kotlin-js-store/yarn.lock
pubnub-gson/pubnub-gson-api/src/main/java/com/pubnub/api/java/PubNub.kt
pubnub-gson/pubnub-gson-api/src/main/java/com/pubnub/api/java/v2/PNConfiguration.kt
pubnub-kotlin/pubnub-kotlin-api/config/ktlint/baseline.xml
pubnub-kotlin/pubnub-kotlin-api/pubnub_kotlin_api.podspec
pubnub-kotlin/pubnub-kotlin-api/src/commonMain/kotlin/com/pubnub/api/PubNub.kt
pubnub-kotlin/pubnub-kotlin-api/src/commonMain/kotlin/com/pubnub/api/models/consumer/access_manager/v3/ChannelGrant.kt
pubnub-kotlin/pubnub-kotlin-api/src/iosMain/kotlin/com/pubnub/api/PubNubImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/jsMain/kotlin/com/pubnub/api/PubNubImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/jvmMain/kotlin/com/pubnub/api/PubNub.kt
pubnub-kotlin/pubnub-kotlin-api/src/nonJvm/kotlin/com/pubnub/api/PubNub.nonJvm.kt
pubnub-kotlin/pubnub-kotlin-core-api/pubnub_kotlin_core_api.podspec
pubnub-kotlin/pubnub-kotlin-core-api/src/commonMain/kotlin/com/pubnub/api/v2/PNConfiguration.kt
pubnub-kotlin/pubnub-kotlin-core-api/src/iosMain/kotlin/com/pubnub/api/v2/PNConfiguration.ios.kt
pubnub-kotlin/pubnub-kotlin-core-api/src/jsMain/kotlin/com/pubnub/api/v2/PNConfiguration.js.kt
pubnub-kotlin/pubnub-kotlin-core-api/src/jvmMain/kotlin/com/pubnub/api/v2/PNConfiguration.jvm.kt
pubnub-kotlin/pubnub-kotlin-core-api/src/jvmMain/kotlin/com/pubnub/api/v2/PNConfiguration.kt
pubnub-kotlin/pubnub-kotlin-impl/config/ktlint/baseline.xml
pubnub-kotlin/pubnub-kotlin-impl/src/integrationTest/kotlin/com/pubnub/api/integration/PublishIntegrationTests.kt
pubnub-kotlin/pubnub-kotlin-impl/src/main/kotlin/com/pubnub/internal/PubNubImpl.kt
pubnub-kotlin/pubnub-kotlin-impl/src/main/kotlin/com/pubnub/internal/v2/PNConfigurationImpl.kt
pubnub-kotlin/pubnub-kotlin-impl/src/main/kotlin/com/pubnub/internal/workers/SubscribeMessageProcessor.kt
pubnub-kotlin/pubnub-kotlin-test/src/commonMain/kotlin/com.pubnub.test/BaseIntegrationTest.kt

so that it can be used in Chat KMP.
There is no need to add getToken to Java.
Deprecated authKey config property.

Added getToken to Kotlin SDK

---

.github/workflows/commands-handler.yml
.github/workflows/release.yml
.github/workflows/run-tests.yml
.github/workflows/run-validations.yml
build-logic/gradle-plugins/src/main/kotlin/com/pubnub/gradle/PubNubKotlinMultiplatformPlugin.kt
pubnub-kotlin/pubnub-kotlin-api/src/jsMain/kotlin/com/pubnub/api/PubNubImpl.kt
pubnub-kotlin/pubnub-kotlin-core-api/src/commonMain/kotlin/com/pubnub/api/enums/PNPushEnvironment.kt
pubnub-kotlin/pubnub-kotlin-core-api/src/commonMain/kotlin/com/pubnub/api/enums/PNPushType.kt
pubnub-kotlin/pubnub-kotlin-impl/src/main/kotlin/com/pubnub/internal/v2/PNConfigurationImpl.kt
pubnub-kotlin/pubnub-kotlin-impl/src/main/kotlin/com/pubnub/internal/workers/SubscribeMessageProcessor.kt

Mostly JS build related changes in preparation for Chat JS.
Also fixes Github runner by changing the Group setting based on new requirement to add "organization/" prefix.

Minor JS changes + runner fix

---

build-logic/gradle-plugins/src/main/kotlin/com/pubnub/gradle/PubNubKotlinMultiplatformPlugin.kt
pubnub-kotlin/pubnub-kotlin-api/config/ktlint/baseline.xml
pubnub-kotlin/pubnub-kotlin-api/src/jsMain/kotlin/Pubnub.d.kt
pubnub-kotlin/pubnub-kotlin-api/src/jsMain/kotlin/com/pubnub/api/PubNubImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/jsMain/kotlin/com/pubnub/kmp/converters.js.kt
pubnub-kotlin/pubnub-kotlin-core-api/src/jsMain/kotlin/com/pubnub/api/v2/PNConfiguration.js.kt
pubnub-kotlin/pubnub-kotlin-impl/config/ktlint/baseline.xml
pubnub-kotlin/pubnub-kotlin-test/src/commonMain/kotlin/com.pubnub.test/BaseIntegrationTest.kt

More JS related fixes to unblock tests in KMP Chat

Fixes for JS tests

---

pubnub-kotlin/pubnub-kotlin-api/pubnub_kotlin_api.podspec
pubnub-kotlin/pubnub-kotlin-api/src/jsMain/kotlin/Pubnub.d.kt
pubnub-kotlin/pubnub-kotlin-api/src/jsMain/kotlin/com/pubnub/api/EndpointImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/jsMain/kotlin/com/pubnub/api/PubNubImpl.kt
pubnub-kotlin/pubnub-kotlin-core-api/pubnub_kotlin_core_api.podspec

Internal changes for enabling Chat JS work

Changes for Chat JS

---

.github/workflows/release/kotlin-maven-publish.sh
build-logic/gradle-plugins/src/main/kotlin/com/pubnub/gradle/PubNubKotlinMultiplatformPlugin.kt
pubnub-kotlin/pubnub-kotlin-api/pubnub_kotlin_api.podspec
pubnub-kotlin/pubnub-kotlin-api/src/jsMain/kotlin/com/pubnub/api/PubNubImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/jsMain/kotlin/com/pubnub/api/endpoints/FetchMessagesImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/jsMain/kotlin/com/pubnub/kmp/factories.js.kt
pubnub-kotlin/pubnub-kotlin-core-api/pubnub_kotlin_core_api.podspec
pubnub-kotlin/pubnub-kotlin-core-api/src/jsMain/kotlin/com/pubnub/kmp/JsMap.kt

Fixes propagation of CRYPTO_IS_CONFIGURED_BUT_MESSAGE_IS_NOT_ENCRYPTED error in messages from PubNub JS

Additional changes for Chat KMP, enable publishing all iOS targets

---

build-logic/gradle-plugins/src/main/kotlin/com/pubnub/gradle/PubNubKotlinMultiplatformPlugin.kt
pubnub-kotlin/pubnub-kotlin-api/pubnub_kotlin_api.podspec
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/PubNubImpl.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/FetchMessages.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/files/PublishFileMessage.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/files/SendFile.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/channel/GetChannelMetadata.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/channel/RemoveChannelMetadata.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/channel/SetChannelMetadata.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/member/GetChannelMembers.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/member/ManageChannelMembers.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/member/RemoveChannelMembers.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/member/SetChannelMembers.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/membership/GetMemberships.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/membership/ManageMemberships.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/uuid/GetAllUUIDMetadata.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/uuid/GetUUIDMetadata.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/uuid/RemoveUUIDMetadata.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/objects/uuid/SetUUIDMetadata.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/pubsub/Publish.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/api/endpoints/pubsub/Signal.ios.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/kmp/converters.kt
pubnub-kotlin/pubnub-kotlin-api/src/appleMain/kotlin/com/pubnub/kmp/factories.ios.kt
pubnub-kotlin/pubnub-kotlin-core-api/pubnub_kotlin_core_api.podspec
pubnub-kotlin/pubnub-kotlin-core-api/src/commonMain/kotlin/com/pubnub/api/models/consumer/objects/membership/MembershipInclude.kt

chore(project): update PubNub Swift SDK dependency (8.2.2)
feat(membership): add support for newly introduced methods regarding Memberships
feat(objc-layer): adjust to the updated method names in the Objective-C KMP layer of the PubNub Swift SDK

Update PubNub Swift SDK dependency
